---
title: "About me"
---

## Work
* 2023 March 1 - Now, post-doctoral researcher in Core Research Institute of Intelligent Robots in Jeonbuk National University, South Korea.

## Education
* 2018 Sep 1 - 2023 Feb 22, Ph.d in Jeonbuk National University in South Korea, majored in Electronic Engineering.

* 2015 Sep 1 - 2018 June 30, M. in Shanghai University of Engineering Science in China, majored in Mechatronic Engineering

* 2011 Sep 1 - 2015 June 30, B. in Jiangxi Agricultural University in China, majored in Vehicle Engineering.

## Award
* 2022 JIANT Fellowship in Recognition of Excellent Research, Joenbuk National University, South Korea.

* 2022 First place in Challenge of PlantCLEF2022, Università di Bologna, Italy.

* 2018 Outstanding Graduates, Shanghai University Of Engineering Science.

* 2017 National Scholarship for Postgraduates, Ministry of Education of China.

* 2017 Merit Student in International Summer School, ITMO University, Russia.

* 2015-2017 First Award Scholarship, Shanghai University Of Engineering Science, China.

* 2016 Third Award of 13th National Postgraduate Mathematical Modeling Competition, China Academic Degrees and Graduate Education Development Center.

* 2016 Third Award of 11th National Postgraduate Electronics Designing Competition, China Academic Degrees and Graduate Education Development Center.

* 2014 Merit Student, Jiangxi Agricultural University, China.

* 2013 Second Award in Jiangxi of National Undergraduate Mathematical Modeling Competition, Chinese Society of Industry and Applied Mathematics, Jiangxi Provincial Department of Education.

* 2013 Merit Based Scholarship, Jiangxi Agricultural University, China.